### PR TITLE
Add /r/ExperiencedDevs

### PR DESCRIPTION
**Pull request by arpankg**
https://www.reddit.com/r/ExperiencedDevs/

### CODE REVIEW

**Comment by fmerian** [comment]
thanks!

**Comment by fmerian** [comment]
ping @ddosify -- is it a subreddit you already experimented with?

**Comment by fmerian** [comment]
ping @kursataktas -- is it a subreddit you already experimented with?

**Comment by kursataktas** [comment]
As far as I remember we didn't experiment on that subreddit.

**Pull request merged**
